# Generated by Django 2.1.3 on 2019-02-19 19:59

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Additional information')),
            ],
        ),
        migrations.CreateModel(
            name='WorksAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincontact', models.BooleanField(default='FALSE', verbose_name='Main Contact?')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.Description')),
                ('name', models.CharField(max_length=40, verbose_name='Client Name')),
                ('address', models.CharField(default='NULL', max_length=120, null=True, verbose_name='Client Address')),
                ('phone', models.CharField(default='NULL', max_length=20, null=True, verbose_name='Phone Number')),
            ],
            bases=('models.description',),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.Description')),
                ('computername', models.CharField(max_length=30, verbose_name='Computer Name')),
                ('operatingsystem', models.CharField(default='NULL', max_length=3, null=True)),
                ('user', models.ManyToManyField(to='models.Client')),
            ],
            bases=('models.description',),
        ),
        migrations.CreateModel(
            name='NetworkEquipment',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.Description')),
                ('connection_type', models.CharField(choices=[('W', 'WiFi'), ('E', 'Ethernet'), ('N', 'No connection')], default='N', max_length=1, verbose_name='Netowrk connection type')),
                ('ip_type', models.CharField(choices=[('D', 'DHCP address'), ('L', 'Static address, local'), ('R', 'Static address, router'), ('N', 'No connection')], default='N', max_length=1, verbose_name='IP addressing type')),
                ('ip_address', models.GenericIPAddressField(default='NULL', null=True, verbose_name='IP Address')),
                ('mac_address', macaddress.fields.MACAddressField(integer=False, max_length=17, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Client')),
            ],
            bases=('models.description',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.Description')),
                ('firstname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='NULL', max_length=20, null=True, verbose_name='Phone Number')),
                ('annoyance', models.PositiveSmallIntegerField(default='0', verbose_name='Annoyance level')),
            ],
            bases=('models.description',),
        ),
        migrations.AddField(
            model_name='worksat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Client'),
        ),
        migrations.AddField(
            model_name='worksat',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Person'),
        ),
        migrations.AddField(
            model_name='client',
            name='employees',
            field=models.ManyToManyField(through='models.WorksAt', to='models.Person'),
        ),
    ]
