# Generated by Django 2.1.3 on 2019-03-07 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190307_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='compmonth',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Recieved Month (enter a number)'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='compyear',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(2000)], verbose_name='Recieved Year (enter a number)'),
        ),
    ]
