# Generated by Django 2.1.3 on 2019-02-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190221_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='operatingsystem',
            field=models.CharField(blank=True, choices=[('W10', 'Windows 10'), ('W7', 'Windows 7'), ('WXP', 'Windows XP'), ('WO', 'Windows Other'), ('MJ', 'MacOS Majovang'), ('MHS', 'MacOS High Siera')], default='', max_length=3, null=True),
        ),
    ]
