# Generated by Django 2.1.3 on 2019-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20190221_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='employedby',
            field=models.ManyToManyField(related_name='employees', through='models.WorksAt', to='models.Client', verbose_name='Employed by'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
