# Generated by Django 2.1.3 on 2019-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20190307_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serialnumber',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
