# Generated by Django 2.1.3 on 2019-02-25 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20190225_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='annoyance',
            field=models.PositiveSmallIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Annoyance level'),
        ),
        migrations.AlterField(
            model_name='worksat',
            name='maincontact',
            field=models.BooleanField(default=False, verbose_name='Main Contact?'),
        ),
    ]
