# Generated by Django 2.1.3 on 2019-03-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20190307_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkequipment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedby', to='models.Client'),
        ),
    ]
