# Generated by Django 2.1.3 on 2019-03-14 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20190312_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=25, verbose_name='Version')),
                ('postedon', models.DateTimeField(default=datetime.datetime.now, verbose_name='Update date')),
                ('author', models.CharField(blank=True, max_length=80, null=True, verbose_name='Update author')),
                ('newstext', models.TextField(verbose_name='News in text format')),
                ('newshtml', models.TextField(verbose_name='New in HTML format')),
            ],
        ),
    ]
