# Generated by Django 2.1.3 on 2019-03-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_systemupdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemupdates',
            name='newshtml',
        ),
        migrations.AddField(
            model_name='systemupdates',
            name='title',
            field=models.CharField(default='1', max_length=120, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
