# Generated by Django 2.1.3 on 2019-03-14 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20190314_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemupdates',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 14, 13, 30, 12, 641984), verbose_name='Created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemupdates',
            name='wassent',
            field=models.BooleanField(default=False, verbose_name='Was sent'),
        ),
        migrations.AlterField(
            model_name='systemupdates',
            name='postedon',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Update time'),
        ),
    ]
