# Generated by Django 2.1.3 on 2019-03-18 19:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='companyname',
            field=models.CharField(default=None, max_length=60, verbose_name='Company name*'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Issue resolved'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolvedby',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Resolved by'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolvedon',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Resolved on'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contactphone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='In the following format: +10000000000x0000, if you need extension', max_length=128, verbose_name='Contact phone number'),
        ),
    ]
