# Generated by Django 2.1.3 on 2019-03-20 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_ticket_unid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemupdates',
            name='postedon',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Update time'),
        ),
    ]
