# Generated by Django 2.1.3 on 2019-03-25 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0014_ticket_assignedto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('author_name', models.CharField(max_length=120, verbose_name='Written by')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Author email')),
                ('description', models.TextField(verbose_name='Comment*')),
                ('senderipaddress', models.GenericIPAddressField(verbose_name='Sender IP address')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Written by (user)')),
                ('initial_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='models.Ticket', verbose_name='Ticket subject')),
            ],
        ),
    ]
