# Generated by Django 2.1.3 on 2019-04-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20190404_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=80, unique=True, verbose_name='Unique ID: ')),
                ('received', models.DateTimeField(verbose_name='received on')),
                ('fromfield', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Sender field')),
                ('fromemail', models.EmailField(blank=True, default=None, max_length=100, null=True, verbose_name='Sender email')),
                ('subject', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Subject')),
                ('body', models.TextField(blank=True, default=None, null=True, verbose_name='Body')),
            ],
        ),
    ]
