# Generated by Django 2.1.3 on 2019-04-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_oneemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneemail',
            name='uniqueid',
            field=models.CharField(max_length=100, unique=True, verbose_name='Unique ID: '),
        ),
    ]
