# Generated by Django 2.1.3 on 2019-04-18 18:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_auto_20190418_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_s',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='In the following format: +10000000000x0000, if you need extension', max_length=128, null=True, verbose_name='Phone Number'),
        ),
    ]
