# Generated by Django 2.1.3 on 2019-04-18 18:56

from django.db import migrations

def transfer_phone_data(apps, schema_editor):
    Client = apps.get_model('models', 'Client')
    for client in Client.objects.all():
        client.phone_s = client.phone
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_client_phone_s'),
    ]

    operations = [
        migrations.RunPython(transfer_phone_data),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='phone_old',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_s',
            new_name='phone',
        ),
    ]
