# Generated by Django 2.1.3 on 2019-04-24 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_secretnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretnote',
            name='expireon',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 18, 36, 15, 937031, tzinfo=utc), null=True, verbose_name='Note expires on'),
        ),
    ]
