# Generated by Django 2.1.3 on 2019-04-24 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_auto_20190424_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretnote',
            name='expireon',
            field=models.DateField(blank=True, default=datetime.date(2019, 5, 1), null=True, verbose_name='Note expires on'),
        ),
    ]
