# Generated by Django 2.1.3 on 2019-04-25 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_auto_20190424_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretnote',
            name='expireon',
            field=models.DateField(blank=True, default=datetime.date(2019, 5, 2), null=True, verbose_name='Note expires on'),
        ),
    ]
