# Generated by Django 2.1.3 on 2019-04-26 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_auto_20190425_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Client Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computername',
            field=models.CharField(max_length=40, verbose_name='Computer Name'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serialnumber',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='admin',
            field=models.CharField(default='administrator', max_length=30, verbose_name='Domain admin username:'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domainnamelong',
            field=models.CharField(max_length=70, verbose_name='Long domain name (.local):'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domainnameshort',
            field=models.CharField(max_length=50, verbose_name='Short domain name:'),
        ),
        migrations.AlterField(
            model_name='othernetworkequipment',
            name='equipmenttype',
            field=models.CharField(max_length=50, verbose_name='Equipment Type'),
        ),
        migrations.AlterField(
            model_name='othernetworkequipment',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='othernetworkequipment',
            name='model',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='othernetworkequipment',
            name='serialnumber',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=60, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='manufacturer',
            field=models.CharField(choices=[('H', 'HP'), ('S', 'Samsung'), ('B', 'Brothers'), ('C', 'Canon'), ('X', 'Xerox'), ('D', 'Dymo'), ('O', 'Other')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printername',
            field=models.CharField(max_length=50, verbose_name='Printer Name'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serialnumber',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='firmwareversion',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Firware version'),
        ),
        migrations.AlterField(
            model_name='router',
            name='model',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='serialnumber',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='settingslink',
            field=models.CharField(blank=True, default='', max_length=130, null=True, verbose_name='Link to settings'),
        ),
        migrations.AlterField(
            model_name='secretnote',
            name='expireon',
            field=models.DateField(blank=True, default=datetime.date(2019, 5, 3), null=True, verbose_name='Note expires on'),
        ),
        migrations.AlterField(
            model_name='secretnote',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Subject*'),
        ),
        migrations.AlterField(
            model_name='systemupdates',
            name='author',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Update author'),
        ),
        migrations.AlterField(
            model_name='systemupdates',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='systemupdates',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='companyname',
            field=models.CharField(max_length=90, verbose_name='Company name*'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolvedby',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Resolved by'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Subject*'),
        ),
    ]
