# Generated by Django 2.1.3 on 2019-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_uploadedfileticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfileticket',
            name='uplfile',
            field=models.FileField(max_length=255, upload_to='tickets/%Y/%m/%d/'),
        ),
    ]
