# Generated by Django 2.1.3 on 2019-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_auto_20190426_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfileticket',
            name='path',
            field=models.CharField(default='.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfileticket',
            name='uplfile',
            field=models.FileField(max_length=255, upload_to=models.CharField(max_length=255)),
        ),
    ]
