# Generated by Django 2.1.3 on 2019-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_auto_20190426_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfileticket',
            name='uplfile',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='<django.db.models.fields.CharField>'),
        ),
    ]
