# Generated by Django 2.1.3 on 2019-04-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_auto_20190426_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfileticket',
            name='path',
        ),
        migrations.AlterField(
            model_name='uploadedfileticket',
            name='uplfile',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
