# Generated by Django 2.1.3 on 2019-04-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0035_auto_20190429_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFileComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uplfile', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('for_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='models.TicketComment')),
            ],
        ),
    ]
