# Generated by Django 2.1.3 on 2019-05-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0037_auto_20190503_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetool',
            name='filename',
            field=models.CharField(max_length=100, null=True, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='maintool',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Tool name'),
        ),
    ]
