# Generated by Django 2.1.3 on 2019-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0038_auto_20190503_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintool',
            name='tool_type_field',
            field=models.CharField(default='', max_length=1),
        ),
    ]
