# Generated by Django 2.1.3 on 2019-05-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0039_maintool_tool_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetool',
            name='filename',
        ),
    ]
