# Generated by Django 2.1.3 on 2019-05-10 18:32

from django.db import migrations, models
import models.router as routermodel


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0040_remove_filetool_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='settings_file',
            field=models.FileField(default=None, null=True, upload_to=routermodel.upload_to_router, verbose_name='Settings file'),
        ),
    ]
