# Generated by Django 2.1.3 on 2019-05-10 19:23

from django.db import migrations, models
import models.router as routermodel


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0041_router_settings_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='settings_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=routermodel.upload_to_router, verbose_name='Settings file'),
        ),
    ]
