# Generated by Django 2.1.3 on 2019-05-13 16:58

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    Clients = apps.get_model('models', 'client')
    for client in Clients.objects.all():
        client.unid = uuid.uuid4()
        client.save()

class Migration(migrations.Migration):

    dependencies = [
        ('models', '0043_router_settings_file_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='unid',
            field=models.UUIDField(blank=True, null=True, editable=False, verbose_name='Unique ID'),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='client',
            name='unid',
            field=models.UUIDField(blank=False, null=False, default=uuid.uuid4, unique=True)
        )
    ]
