# Generated by Django 2.1.3 on 2019-05-13 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0044_client_unid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='unid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique ID'),
        ),
    ]
