# Generated by Django 2.1.3 on 2019-05-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0045_auto_20190513_1305'),
    ]

    operations = [
        migrations.RenameField('systemupdates', 'title', 'tittle'),
        migrations.AlterField(
            model_name='systemupdates',
            name='tittle',
            field=models.CharField(default='', max_length=160, verbose_name='Tittle'),
        ),
    ]
