# Generated by Django 2.1.3 on 2019-05-15 19:25

from django.db import migrations, models
import models.updates as upd


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0047_auto_20190513_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemupdates',
            name='postedon',
            field=models.DateTimeField(default=upd.time_now, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='systemupdates',
            name='createdon',
            field=models.DateTimeField(default=upd.time_now, verbose_name='Created time'),
        ),
    ]
