# Generated by Django 2.2.2 on 2019-06-14 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0048_auto_20190515_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='manufacturer',
            field=models.CharField(choices=[('D', 'DELL'), ('H', 'HP'), ('L', 'Lenovo'), ('M', 'Microsoft'), ('G', 'Apple'), ('A', 'Asus'), ('S', 'Sony'), ('C', 'Acer'), ('O', 'Other')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='printer',
            name='prmonth',
            field=models.IntegerField(blank=True, default=6, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Recieved Month (enter a number)'),
        ),
    ]
