# Generated by Django 2.2 on 2019-07-01 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0049_auto_20190614_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='prmonth',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Recieved Month (enter a number)'),
        ),
    ]
