# Generated by Django 2.2.3 on 2019-07-29 17:57

from django.db import migrations, models
import models.wikiarticle as wikiart
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0050_auto_20190701_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120, verbose_name='Word')),
            ],
        ),
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postedon', models.DateTimeField(default=wikiart.time_now, verbose_name='Update time')),
                ('createdon', models.DateTimeField(default=wikiart.time_now, verbose_name='Created time')),
                ('title', models.CharField(default='', max_length=160, verbose_name='Title')),
                ('unid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('article', models.TextField(verbose_name='Wiki article')),
                ('keywords', models.ManyToManyField(to='models.Keywords', verbose_name='Keywords')),
            ],
        ),
    ]
