# Generated by Django 2.2.3 on 2019-08-05 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0051_keywords_wikiarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintool',
            name='publicinlist',
            field=models.BooleanField(default=True, verbose_name='Public tool in list'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='prmonth',
            field=models.IntegerField(blank=True, default=8, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Recieved Month (enter a number)'),
        ),
    ]
