# Generated by Django 2.2.3 on 2019-08-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0052_auto_20190805_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretnote',
            old_name='reads_left',
            new_name='reads_max',
        ),
        migrations.AddField(
            model_name='secretnote',
            name='reads_used',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of reads used'),
        ),
    ]
