# Generated by Django 2.1.3 on 2019-05-22 18:16

import api_app.model_files.apikeysmodel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=40, null=True, verbose_name='API Key name')),
                ('secret_api_key', models.CharField(max_length=200, unique=True, verbose_name='API Key')),
                ('createdon', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('expireon', models.DateField(blank=True, default=api_app.model_files.apikeysmodel.expiration_date, null=True, verbose_name='Expiration date')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Additional information')),
            ],
        ),
    ]
