# Generated by Django 2.1.3 on 2019-02-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkequipment',
            name='connection_type',
            field=models.CharField(choices=[('N', 'No connection'), ('W', 'WiFi'), ('E', 'Ethernet')], default='N', max_length=1, verbose_name='Netowrk connection type'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='ip_type',
            field=models.CharField(choices=[('N', 'No connection'), ('D', 'DHCP address'), ('L', 'Static address, local'), ('R', 'Static address, router')], default='N', max_length=1, verbose_name='IP addressing type'),
        ),
    ]
