# Generated by Django 2.1.3 on 2019-02-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20190226_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='recdata',
            new_name='recdate',
        ),
    ]
