# Generated by Django 2.1.3 on 2019-02-26 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20190226_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='recdate',
        ),
        migrations.AddField(
            model_name='computer',
            name='compmonth',
            field=models.IntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Recieved Month (enter a number)'),
        ),
        migrations.AddField(
            model_name='computer',
            name='compyear',
            field=models.IntegerField(blank=True, default=2019, null=True, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(2000)], verbose_name='Recieved Year (enter a number)'),
        ),
    ]
