# Generated by Django 2.1.3 on 2019-02-27 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20190226_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainnameshort', models.CharField(max_length=30, verbose_name='Short domain name:')),
                ('domainnamelong', models.CharField(max_length=50, verbose_name='Long domain name (.local):')),
                ('admin', models.CharField(default='administrator', max_length=15, verbose_name='Domain admin username:')),
                ('dnsip', models.GenericIPAddressField(default='192.168.0.10', protocol='IPv4', verbose_name='Domain dns IP: ')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description: ')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='models.Client', verbose_name='Company: ')),
                ('server', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain', to='models.Computer', verbose_name='Domain server: ')),
            ],
        ),
    ]
