# Generated by Django 2.1.3 on 2019-02-27 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('networkequipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.NetworkEquipment')),
                ('printername', models.CharField(max_length=30, verbose_name='Printer Name')),
                ('manufacturer', models.CharField(choices=[('H', 'HP'), ('B', 'Brothers'), ('C', 'Canon'), ('D', 'Dymo'), ('O', 'Other')], default='H', max_length=1)),
                ('printertype', models.CharField(choices=[('BL', 'Black and white Laser'), ('CL', 'Color Laser'), ('BI', 'Black and white Ink'), ('CI', 'Color Ink'), ('L', 'Label'), ('O', 'Other')], default='BL', max_length=2)),
                ('model', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('prmonth', models.IntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Recieved Month (enter a number)')),
                ('pryear', models.IntegerField(blank=True, default=2019, null=True, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(2000)], verbose_name='Recieved Year (enter a number)')),
                ('serialnumber', models.CharField(blank=True, default='', max_length=25, null=True)),
            ],
            bases=('models.networkequipment',),
        ),
    ]
