# Generated by Django 2.1.3 on 2019-03-01 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('networkequipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.NetworkEquipment')),
                ('manufacturer', models.CharField(choices=[('S', 'Sonicwall'), ('N', 'Netgear'), ('A', 'Asus'), ('L', 'Linksys'), ('C', 'Cisco'), ('U', 'Ubiquity'), ('T', 'TP Link'), ('O', 'Other')], default='S', max_length=1)),
                ('model', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('serialnumber', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('externalip', models.GenericIPAddressField(blank=True, default='', null=True, protocol='IPv4', verbose_name='External IP address')),
                ('settingslink', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Link to settings')),
                ('firmwareversion', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Firware version')),
            ],
            bases=('models.networkequipment',),
        ),
        migrations.AlterField(
            model_name='computer',
            name='compmonth',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Recieved Month (enter a number)'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='manufacturer',
            field=models.CharField(choices=[('H', 'HP'), ('B', 'Brothers'), ('C', 'Canon'), ('X', 'Xerox'), ('D', 'Dymo'), ('O', 'Other')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printertype',
            field=models.CharField(choices=[('BL', 'Black and white, Laser'), ('CL', 'Color, Laser'), ('BI', 'Black and white, Ink'), ('CI', 'Color, Ink'), ('L', 'Label'), ('O', 'Other')], default='BL', max_length=2),
        ),
        migrations.AlterField(
            model_name='printer',
            name='prmonth',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Recieved Month (enter a number)'),
        ),
    ]
