# Generated by Django 2.1.3 on 2019-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20190301_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='computer', to='models.Person'),
        ),
    ]
