# Generated by Django 2.1.3 on 2019-03-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20190301_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherNetworkEquipment',
            fields=[
                ('networkequipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.NetworkEquipment')),
                ('equipmenttype', models.CharField(max_length=30, verbose_name='Equipment Type')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Manufacturer')),
                ('model', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Model')),
                ('serialnumber', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Serial number')),
            ],
            bases=('models.networkequipment',),
        ),
    ]
