# Generated by Django 2.1.3 on 2019-03-20 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20190318_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
