# Generated by Django 2.1.3 on 2019-03-04 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_othernetworkequipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksat',
            name='client',
        ),
        migrations.RemoveField(
            model_name='worksat',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='employedby',
        ),
        migrations.AddField(
            model_name='person',
            name='employedby',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='models.Client', verbose_name='Employed by'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WorksAt',
        ),
    ]
