# Generated by Django 2.1.3 on 2019-03-20 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_ticket_unid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unid',
            field=models.UUIDField(default=uuid.UUID('0208e49c-cf4a-4aaa-946e-e716126a292f'), editable=False, unique=True),
        ),
    ]
