# Generated by Django 2.1.3 on 2019-03-04 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20190304_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='employedby',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='models.Client', verbose_name='Employed by'),
        ),
    ]
