# Generated by Django 2.1.3 on 2019-03-20 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20190320_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unid',
            field=models.UUIDField(default=uuid.UUID('9a03a61b-f108-45ff-8fab-bb6f389a6ecc'), editable=False, unique=True),
        ),
    ]
